name: Production Deploy

on:
  push:
    branches:
      - master

jobs:
  # ФРОНТЕНД
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: SSH_HOST
    steps:
      - name: Start deployment
        run: echo "Starting frontend deployment process..."
      
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      #     cache: 'npm'
      #     cache-dependency-path: frontend/package-lock.json

      # - name: Install & Build Frontend
      #   run: |
      #     cd frontend
      #     npm ci
      #     npm run build

      - name: Debug Secrets Availability
        if: always()
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "❌ ERROR: SSH_HOST is EMPTY! Check your GitHub Secrets settings."
            exit 1
          else
            echo "✅ OK: SSH_HOST is found (length is not zero)."
          fi
          
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "❌ ERROR: SSH_KEY is EMPTY!"
          else
             echo "✅ OK: SSH_KEY is found."
          fi

      - name: Debug Connectivity
        run: |
          echo "Checking port..."
          nc -v -z -w 5 ${{ secrets.SSH_HOST }} ${{ secrets.SSH_PORT }}
      
      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "frontend/*" # TODO: в залежності де build: dist/* або build/*
          target: "/var/www/demo.harkushyn.com"
          strip_components: 1 # щоб не копіювати папку frontend


  # БЕКЕНД
  deploy-backend:
    runs-on: ubuntu-latest
    environment: SSH_HOST
    needs: deploy-frontend
    steps:
      - name: Start backend deployment
        run: echo "Starting backend deployment process..."

      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/anon-confess
            git pull origin master
            docker compose up -d --build backend
            docker image prune -f
